CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS profile_db;
CREATE DATABASE IF NOT EXISTS post_db;
CREATE DATABASE IF NOT EXISTS notification_db;

GRANT ALL PRIVILEGES ON user_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON profile_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON post_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON notification_db.* TO 'app'@'%';

FLUSH PRIVILEGES;
