server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: lax

logging:
  file:
    name: ./log/application.log
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        session: DEBUG

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:mysql://localhost/user_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root@123}
    tomcat:
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:CHANGE_YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:CHANGE_YOUR_GOOGLE_SECRET_CLIENT_ID}
            scope:
              - email
              - profile

---
spring:
  config:
    activate:
      on-profile: docker-compose
  session:
    store-type: none
  datasource:
    url: 'jdbc:mysql://mysql/${MYSQL_DATABASE:user_db}'
    username: app
    password: app
  data:
    redis:
      host: redis
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD:devpassword}

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  session:
    store-type: none
  data:
    redis:
      repositories:
        enabled: false
